import type { ArchetypeId, SetupContext, SkillFocus, PlayerLevel, TimeProfile } from '../../model'

/**
 * Diagnostic-spine dimensions.
 *
 * **Role (post-2026-05-07 D138 resolution).** This module owns the
 * shared dimension constants and their types for the live generated-
 * plan diagnostic (`app/src/domain/generatedPlanDiagnostics.ts`). It
 * intentionally does NOT own a coverage audit anymore — the catalog-
 * coverage detection diagnostic is `app/src/data/focusCoverageAudit.ts`,
 * which is the canonical surface (snapshot regression test in
 * `app/src/data/__tests__/focusCoverageAudit.test.ts`, markdown report
 * generated by `app/scripts/generate-coverage-report.ts` and committed
 * at `docs/reviews/2026-05-04-focus-coverage-audit.md`).
 *
 * The pre-2026-05-07 file also exposed `buildFocusReadinessAudit`,
 * `evaluateFocusReadinessCell`, a gap-card / activation-manifest
 * remediation API (`FocusReadinessGapCard`, `ActivationBatchManifest`,
 * `validateFocusReadinessGapCard`, `validateActivationBatchManifest`,
 * `canTransitionReadinessStatus`, `isReadinessStatus`,
 * `isReadinessRiskBucket`, `hasPerSlotSwapCoverage`), and the rich
 * `ReadinessStatus` / `ReadinessRiskBucket` / `FocusReadinessCellReport`
 * type tower. Those were a parallel implementation of catalog-coverage
 * detection authored on `feat/focus-coverage-readiness`. At the
 * 2026-05-05 merge they lost the canonicality contest to
 * `focusCoverageAudit` (which had a snapshot test, a markdown report,
 * and walked the user-facing 5-tier `SkillLevel`). The remediation API
 * was never wired up — no script, plan, or surface ever consumed gap
 * cards or activation manifests. The audit logic was tested only by
 * its own self-test. `D138` resolved this in favor of the live
 * `focusCoverageAudit` and pruned the dead surface; only the
 * dimensions consumed by `generatedPlanDiagnostics` remain.
 *
 * If a future need surfaces for a remediation tracker (gap cards,
 * activation manifests, status workflows like
 * `failing → source_candidate → fixed_pending_verification → verified`),
 * re-author it from the new context rather than restoring this file's
 * previous contents — those types were speculative and never met
 * production. Likely homes: a JSON gap registry under `docs/`, or a
 * new typed module composed against whichever live diagnostic the
 * tracker is targeting.
 *
 * Keep this file compatible with `generatedPlanDiagnostics.ts`'s
 * imports.
 */

export type VisibleFocus = Extract<SkillFocus, 'pass' | 'serve' | 'set'>

export type ReadinessConfigurationId = ArchetypeId

export interface ReadinessConfiguration {
  readonly id: ReadinessConfigurationId
  readonly context: Pick<SetupContext, 'playerMode' | 'netAvailable' | 'wallAvailable'>
}

export const VISIBLE_FOCUSES: readonly VisibleFocus[] = ['pass', 'serve', 'set'] as const

export const PLAYER_LEVELS: readonly PlayerLevel[] = [
  'beginner',
  'intermediate',
  'advanced',
] as const

export const READINESS_DURATIONS: readonly TimeProfile[] = [15, 25, 40] as const

export const READINESS_CONFIGURATIONS: readonly ReadinessConfiguration[] = [
  {
    id: 'solo_net',
    context: {
      playerMode: 'solo',
      netAvailable: true,
      wallAvailable: false,
    },
  },
  {
    id: 'solo_wall',
    context: {
      playerMode: 'solo',
      netAvailable: false,
      wallAvailable: true,
    },
  },
  {
    id: 'solo_open',
    context: {
      playerMode: 'solo',
      netAvailable: false,
      wallAvailable: false,
    },
  },
  {
    id: 'pair_net',
    context: {
      playerMode: 'pair',
      netAvailable: true,
      wallAvailable: false,
    },
  },
  {
    id: 'pair_open',
    context: {
      playerMode: 'pair',
      netAvailable: false,
      wallAvailable: false,
    },
  },
] as const
